from __future__ import annotations

from ..identifiers import SERVICE_CLASS

PALETTE_CATEGORY_VIZ = f"{SERVICE_CLASS}.viz"
PALETTE_CATEGORY_CONTROL = f"{SERVICE_CLASS}.control"
PALETTE_CATEGORY_EXPR = f"{SERVICE_CLASS}.expr"
PALETTE_CATEGORY_CANVAS = f"{SERVICE_CLASS}.canvas"
PALETTE_CATEGORY_ROUTING = f"{SERVICE_CLASS}.routing"
